### ISSUE TITLE
Overscaled UI on HiDPI displays (Mac)

### ISSUE THREAD

**Issue by septag** [kyle-sylvestre/mightygrep-misc#1]
The UI is overscaled, on HiDPI monitors. which is basically all MacBook displays.
I can give more details, but i guess just running it on such displays would make it pretty obvious.

**Comment by kyle-sylvestre** [comment]
Thank you for the bug report. Please test this demo with HiDPI changes added and see if the window is no longer overscaled.

[mightygrep-demo-hidpi-fix.zip](https://github.com/kyle-sylvestre/mightygrep-misc/files/13909709/mightygrep-demo-hidpi-fix.zip)

**Comment by septag** [comment]
sorry for the late reply.
yes it's fixed in the latest version. thank you
