### ISSUE TITLE
Archive files

### ISSUE THREAD

**Issue by harryray33** [kyle-sylvestre/mightygrep-misc#2]
Is it possible to search within RAR and 7z files, If not, will any future releases be able to search within archive files?

Thanks.

**Comment by kyle-sylvestre** [comment]
Searching files/folders within archive files is not supported but that would be a nice feature to have. I'll add it to the roadmap.

**Comment by harryray33** [comment]
Brilliant, thanks. I have a lot of 7z, and quite a few RAR files, and I frequently need to check for text strings within the archived files.
Will mightygrep search within all files, irrespective of extension...text, binary etc?

**Comment by kyle-sylvestre** [comment]
yes mightygrep searches within all files as-is, it will not convert files to plaintext (ex: pdf, doc)
