### ISSUE TITLE
Request: using WinMain (windows app) instead of main (Console)

### ISSUE THREAD

**Issue by septag** [kyle-sylvestre/mightygrep-misc#3]
Hi,
The problem of MightyGrep having a console is that when you call it from command-line (including all cmd-line file managers like FarManager), it will freeze the current command line until we quit the MightyGrep and kind of mess it up.

![image](https://github.com/user-attachments/assets/50f13c0d-7502-42ff-96f3-61667430197d)

so since this is a GUI app, is it possible to use WinMain and get rid of the console ? 

Thanks

**Comment by kyle-sylvestre** [comment]
It's already using WinMain, it calls AttachConsole when it detects a command prompt. I'll make console logging an opt-in feature with a command line flag in 0.14.0

**Comment by septag** [comment]
I see. thanks!

**Comment by kyle-sylvestre** [comment]
released 0.14.0
